services:
  zap:
    image: zaproxy/zap-stable
    container_name: zap
    ports:
      - "8080:8080"
    command: ["zap.sh", "-daemon", "-host", "0.0.0.0", "-port", "8080", "-config", "api.disablekey=true"]
    environment:
      - ZAP_API_DISABLEKEY=true
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080"]
      interval: 10s
      retries: 5
      start_period: 20s
      timeout: 5s
    networks:
      - scanner_network


  django:
    build: amit1020/amit-django-api-server
    container_name: django-scanner
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    depends_on:
      zap:
        condition: service_healthy
    environment:
      - ZAP_HOST=http://zap:8080  # Make sure Django uses 'zap' as hostname
    networks:
      - scanner_network

networks:
  scanner_network:
    driver: bridge
